version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  flask-api:
    build: ./backend
    container_name: flask-api
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    depends_on:
      - mongo

volumes:
  mongo_data:
