- name: Ansible
  hosts: all
  become: yes
  vars:
    backend_ip: "{{ lookup('pipe', 'terraform output -raw backend_server_private_ip') }}"

  tasks:
    - name: Update all packages (Amazon Linux 2023+ uses dnf)
      dnf:
        name: '*'
        state: latest

    - name: Install python3-pip and git
      dnf:
        name:
          - python3-pip
          - git
        state: present

    - name: Install Python requests package with pip3
      pip:
        name: requests
        executable: pip3

    - name: Clone pokemon3 repo from GitHub
      git:
        repo: https://github.com/nadine2000/pokemon3
        dest: /home/ec2-user/pokemon3
        update: yes

    - name: Insert API_BASE_URL into db.py as first line
      lineinfile:
        path: /home/ec2-user/pokemon3/frontend/db.py
        line: "API_BASE_URL = \"http://{{ backend_ip }}:5000\""
        insertafter: BOF
