---
- name: Ansible
  hosts: all
  become: yes

  tasks:
    - name: Update all packages (Amazon Linux 2023+ uses dnf)
      dnf:
        name: '*'
        state: latest

    - name: Install python3-pip and git
      dnf:
        name:
          - python3-pip
          - git
        state: present

    - name: Install Python requests package with pip3
      pip:
        name: requests
        executable: pip3

    - name: Clone pokemon3 repo from GitHub
      git:
        repo: https://github.com/nadine2000/pokemon3
        dest: /home/ec2-user/pokemon3
        update: yes
        
    - name: Change ownership of the cloned repo to ec2-user
      file:
        path: /home/ec2-user/pokemon3
        owner: ec2-user
        group: ec2-user
        recurse: yes
