- name: userdata.sh with Ansible
  hosts: frontend
  become: true

  tasks:
    - name: Ubuntu
      apt:
        update_cache: yes
      when: ansible_facts['pkg_mgr'] == "apt"

    - name: Amazon Linux
      yum:
        name: "*"
        state: latest
      when: ansible_facts['pkg_mgr'] == "yum"

    - name: Install python3-pip and git
      package:
        name: 
          - python3-pip
          - git
        state: present

    - name: Install requests using pip3
      pip:
        name: requests
        executable: pip3

    - name: Clone the GitHub repo
      git:
        repo: https://github.com/nadine2000/pokemon3
        dest: /home/ubuntu/pokemon3
        clone: yes
        update: yes

    - name: Run the Python script
      command: python3 main.py
      args:
        chdir: /home/ubuntu/pokemon3/frontend
